theme: jekyll-theme-chirpy 

title: Perevodildo's schizo rambling newsletter 

description: A new home for lengthy descriptions and miscellaneous posts. 

defaults:
  -
    scope: 
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
